### ISSUE TITLE
MokaHR招聘前端/后端/NLP

### ISSUE THREAD

**Issue by fakefish** [neitui/jobs#1]
## 招聘职位
前端/后端/NLP
## 公司

**Moka简介**

**我们是谁？**
Moka创始团队来自硅谷，毕业于伯克利、斯坦福计算机专业，之前在Facebook，Turo，SignalFx等公司做过产品和技术相关工作。所以总体来说公司气氛比较硅谷范儿，工作方式很open，很产品和技术driven，鼓励大家创新，think out of the box。技术团队背景多样，共性是都是有产品思维的geek，热爱折腾新技术，却又喜欢站在用户的角度思考工程问题，不局限于自己适应的技术栈，做正确的事而不是简单的事，江湖俗称product engineer。

**我们在做什么？**
我们相信人才是公司最重要的资产，招聘是重中之重。我们想要解决目前企业中普遍存在的招聘混乱低效的问题，帮助企业将招聘变成竞争优势。我们的产品“Moka"（ http://www.mokahr.com ）是一个SaaS架构的招聘CRM，致力于将先进的招聘理念与前沿的技术相融合，切实地解决企业招聘过程中的痛点，为hr带来全新的工作方式。近年来企业服务正在持续升温，错过了社交网络、移动互联网、O2O等一波又一波浪潮，相信你不会想再次错过这波SaaS的强势崛起！ 我们在刚成立不久就拿到国内顶级VC的数百万天使轮投资，团队现已初具规模，但仍在发展壮大中。

**我们能给你什么？**
• 早期期权
• 开放的工作环境，我们随时倾听你对公司发展的任何意见，并全力支持你的个人发展。
• 全新 RMBP 及显示器。 每月团建吃喝玩腐败、无限量零食、饮料、免费午餐水果下午茶、人体工学座椅、全自动胶囊咖啡机、 honeywell 空气净化器

## 内推邮箱
`wangjiayu@mokahr.com`

## 职位描述

**前端**

1、根据设计师的Mock像素级地实现产品；
2、全面负责前端开发；

我们希望你：

1.    丰富的web开发经验，JS烂熟于胸，HTML/CSS手到擒来
2.    熟悉一种web框架，如React+Flux, Angular.js, Backbone.js, Ember.js等
3.    有较好的计算机基础知识积累，了解服务器端开发技术
4.    聪明，自信，善于分析和解决问题，优秀的学习能力，热爱技术

加分项：

1.    开源爱好者或喜欢业余时间做些有趣的小玩意儿
2.    有复杂项目的前端架构设计经验
3.    熟悉React+Redux
4.    熟悉NodeJS

**后端**

1、丰富的后端开发经验，精通以下语言的一种或多种：Node.js，Python，Ruby，PHP，Java，C++ ，了解Node.js优先
2、熟练掌握web应用服务器端技术，熟知网络相关知识和数据库
3、了解一些其他的后端基础知识，如缓存、OS、消息队列、容器技术等 
4、聪明，自信，善于分析和解决问题，优秀的学习能力，热爱技术 

我们希望你： 

1、开源爱好者或喜欢业余时间做些有趣的小玩意儿 
2、有复杂项目的后端架构设计经验 
3、熟悉前端开发技术

**自然语言处理**

1. 负责业务数据的分析、理解和挖掘，驱动产品创新
2. 根据业务场景建立模型，并利用NLP、机器学习等方法解决如命名实体识别、语义分析、匹配等实际问题

我们希望你：

1. 计算机或相关专业硕士及以上学历
2. 丰富的中文NLP/NLU经验，丰富的机器学习经验（深度学习经验更佳）。主导过NLP项目（或参与过大型NLP项目）
3. 熟练使用NLP/ML相关的开源工具和开发框架，如NLTK、stanfordNLP、TensorFlow、Theano、Caffe等
4. 主人翁意识，以结果为导向。思路灵活，善于创新，不为固有方法所束缚。如寻找相关paper并快速验证效果、穷尽办法收集training data等
5. 优秀的开发能力，能够独立从0搭建高质量的NLP项目

## 地理位置
北京-中关村地铁站附近

**Comment by MAJIANYANG666** [comment]
来看看
