### ISSUE TITLE
百度招聘前端

### ISSUE THREAD

**Issue by xiaoqiang-zhao** [neitui/jobs#3]
## 公司

百度-创新业务部

## 内推邮箱

zhaoxiaoqiang@baidu.com

## 职位描述

职位年薪：25~50w
工作经验: 2年以上
最低学历: 本科
工作地点: 北京-海淀区

工作职责:
1、负责公司产品Web前端研发，包括 PC 端管理系统和移动应用；
2、与产品经理、设计师、后端工程师紧密工作在一起，负责公司各产品易用性改进、界面技术优化和网站性能优化；
3、Web前沿技术研究和新技术调研。

资格要求：
1、HTML、CSS、JS 基础扎实，具备移动端开发经验；
2、熟练使用 yarn、npm、git 等工具；
3、掌握 MVVM 框架的原理和使用，熟练使用 Vue 或 React；
4、熟悉W3C标准，对表现与数据分离、Web语义化等有较为深刻的理解；
5、熟悉用户交互设计理论，热衷分析并改善产品的用户体验；
6、具备工程化的前端思维，具备较好的问题分析与解决能力；
7、思路清晰，具备良好的沟通能力和团队协作精，善于学习、总结，乐于分享。

具备以下资格优先：
1、熟练使用Linux，掌握 NodeJs、PHP、Ruby、Java、Python 中的一种或多种；
2、能够理解数据结构和算法设计，具有一定的软件工程意识；
3、对下新技术有强烈兴趣，有良好的学习能力和强烈的进取心；
4、有较强的学习能力和较高的学习热情，具备积极向上的心态，有一定抗压能力。

关于我们团队：
1、前端 20+成员，多层技术 T 队满足你的成长需求；
2、完善的导师机制，每个新人都有高你一个技术等级的导师；
3、每周技术分享；
4、新成立的部门没有历史包袱。

其他福利：
1、免费开放：健身房、瑜伽室、台球室、羽毛球场等等；
2、免费零食，每日水果供应；
3、公司班车点：安河桥北、西北旺、生命科学园、回龙观等地铁站。

## 地理位置
中关村科技园二期

**Comment by zhaozhuoboy** [comment]
还差一年:see_no_evil:
